# -*- coding: utf-8 -*-
"""Breast_Cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFjASYdPA5LMEIDB4UY9aodTNy5dui2-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.image as mpimg
from sklearn.preprocessing import LabelEncoder as labelencoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

Breast_cancer=pd.read_csv('data.csv')

Breast_cancer.sample(5)

Breast_cancer.shape

Breast_cancer.describe()

Breast_cancer.dtypes

Breast_cancer.isnull().sum()

Breast_cancer=Breast_cancer.drop(['Unnamed: 32'],axis=1)

Breast_cancer.dtypes

Breast_cancer.shape

Breast_cancer.duplicated().sum()

x=Breast_cancer.drop(['diagnosis'],axis=1)
y=Breast_cancer['diagnosis']

diagnosis=labelencoder()
Breast_cancer['diagnosis']=diagnosis.fit_transform(Breast_cancer['diagnosis'])

Breast_cancer['diagnosis']

model=DecisionTreeClassifier()

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=2)

model.fit(X_train,Y_train)

m=model.predict(X_train)
k=accuracy_score(Y_train,m)
print(k*100)

input=[842302,17.99,	10.38,	122.8,	1001,	0.1184,	0.2776,	0.3001,	0.1471,	0.2419,	0.07871,	1.095,	0.9053,	8.589,	153.4,	0.006399,	0.04904,	0.05373,	0.01587,	0.03003,	0.006193,	25.38,	17.33,	184.6,	2019,	0.1622,	0.6656,	0.7119,	0.2654,	0.4601,	0.1189]
feature=['id','radius_mean','texture_mean','perimeter_mean','area_mean','smoothness_mean','compactness_mean','concavity_mean','concave points_mean','symmetry_mean','fractal_dimension_mean','radius_se','texture_se','perimeter_se','area_se','smoothness_se','compactness_se','concavity_se','concave points_se','symmetry_se','fractal_dimension_se','radius_worst','texture_worst','perimeter_worst','area_worst','smoothness_worst','compactness_worst','concavity_worst','concave points_worst','symmetry_worst','fractal_dimension_worst']
#id	diagnosis	radius_mean	texture_mean	perimeter_mean	area_mean	smoothness_mean	compactness_mean	concavity_mean	concave points_mean	symmetry_mean	fractal_dimension_mean	radius_se	texture_se	perimeter_se	area_se	smoothness_se	compactness_se	concavity_se	concave points_se	symmetry_se	fractal_dimension_se	radius_worst	texture_worst	perimeter_worst	area_worst	smoothness_worst	compactness_worst	concavity_worst	concave points_worst	symmetry_worst	fractal_dimension_worst
input=np.asarray(input)
input=input.reshape(1,-1)
df=pd.DataFrame(input,columns=feature)
prediction=model.predict(df)
print(prediction)

cm=classification_report(Y_train,m)
print(cm)

cp=confusion_matrix(Y_train,m)
sns.heatmap(cp,annot=True)
plt.show()